#!/usr/bin/env python3
"""
LLM-Powered Intelligent Web Fuzzer

Uses LLM to generate context-aware payloads for:
- SQL injection
- XSS
- Command injection
- Path traversal
- Authentication bypass
- And more...

NO STATIC PAYLOAD LISTS - Everything generated by LLM based on context.
"""

from typing import Dict, List, Optional, Any
import sys
from pathlib import Path

# Add paths for cross-package imports
# packages/web/fuzzer.py -> repo root
sys.path.insert(0, str(Path(__file__).parents[2]))

from core.logging import get_logger
from core.security.redaction import redact_secrets
from packages.llm_analysis.llm.providers import LLMProvider
from packages.web.client import WebClient

logger = get_logger()


class WebFuzzer:
    """LLM-powered intelligent fuzzer - no static payloads."""

    def __init__(self, client: WebClient, llm: LLMProvider):
        self.client = client
        self.llm = llm

        # Vulnerability findings
        self.findings: List[Dict[str, Any]] = []

        logger.info("Intelligent web fuzzer initialized (LLM-powered)")

    def fuzz_parameter(self, url: str, param_name: str, param_type: str = "text",
                      vulnerability_types: Optional[List[str]] = None) -> List[Dict]:
        """
        Fuzz a specific parameter with LLM-generated payloads.

        Args:
            url: Target URL
            param_name: Parameter name
            param_type: Parameter type (text, number, email, etc.)
            vulnerability_types: Types to test (sqli, xss, etc.)

        Returns:
            List of findings
        """
        if vulnerability_types is None:
            vulnerability_types = ['sqli', 'xss', 'command_injection', 'path_traversal']

        logger.info(
            "Fuzzing parameter "
            f"'{param_name}' at {redact_secrets(url, reveal_secrets=self.client.reveal_secrets)}"
        )

        findings = []

        for vuln_type in vulnerability_types:
            payloads = self._generate_payloads(param_name, param_type, vuln_type)

            # Stop at the first confirmed finding per (parameter, vuln_type) pair --
            # one confirmed payload is enough evidence; reporting all 10 that match
            # the same heuristic is noise, not signal.
            for payload in payloads:
                finding = self._test_payload(url, param_name, payload, vuln_type)
                if finding:
                    findings.append(finding)
                    self.findings.append(finding)
                    break  # confirmed for this vuln_type, move to next

        return findings

    def _generate_payloads(self, param_name: str, param_type: str,
                          vuln_type: str, count: int = 10) -> List[str]:
        """Generate intelligent payloads using LLM."""
        system = (
            "You are a senior penetration tester generating test payloads for authorised security testing. "
            "Respond with a JSON object containing exactly one key 'payloads' whose value is an array of strings. "
            "No explanation, no markdown, no extra keys. Output only the JSON object."
        )
        prompt = (
            f"Generate {count} payloads to test a parameter named '{param_name}' "
            f"(type: {param_type}) for {vuln_type} vulnerabilities. "
            "Tailor payloads to the parameter name and type. "
            "Include basic, advanced, and evasion variants."
        )

        schema = {"payloads": "array of payload strings"}

        try:
            result, _ = self.llm.generate_structured(
                prompt=prompt,
                schema=schema,
                system_prompt=system,
            )
            payloads = result.get('payloads', [])
            if payloads:
                logger.info(f"Generated {len(payloads)} payloads for {vuln_type}")
                return [str(p) for p in payloads if p]
        except Exception as e:
            logger.debug(f"LLM payload generation failed: {e}")

        return self._get_basic_payloads(vuln_type)

    def _get_basic_payloads(self, vuln_type: str) -> List[str]:
        """Fallback basic payloads when LLM fails."""
        basic_payloads = {
            'sqli': ["' OR '1'='1", "' OR 1=1--", "'; DROP TABLE users--"],
            'xss': ["<script>alert('XSS')</script>", "<img src=x onerror=alert(1)>"],
            'command_injection': ["; ls", "| whoami", "`cat /etc/passwd`"],
            'path_traversal': ["../../../etc/passwd", "..\\..\\..\\windows\\win.ini"],
        }
        return basic_payloads.get(vuln_type, ["test"])

    def _test_payload(self, url: str, param_name: str, payload: str,
                     vuln_type: str) -> Optional[Dict]:
        """Test a payload against endpoint."""
        try:
            # Send request with payload
            response = self.client.get(url, params={param_name: payload})

            # Analyze response using LLM
            is_vulnerable = self._analyze_response(response, payload, vuln_type)

            if is_vulnerable:
                logger.warning(f"Potential {vuln_type} found in {param_name}")
                return {
                    'url': redact_secrets(url, reveal_secrets=self.client.reveal_secrets),
                    'parameter': param_name,
                    'payload': payload,
                    'vulnerability_type': vuln_type,
                    'status_code': response.status_code,
                    'response_length': len(response.content),
                }

        except Exception as e:
            logger.debug(f"Error testing payload: {e}")

        return None

    def _analyze_response(self, response, payload: str, vuln_type: str) -> bool:
        """Determine whether a response indicates exploitation.

        Uses tight evidence-based heuristics. A positive match requires
        unambiguous server-side execution evidence, not just reflection of
        the payload or presence of a keyword in marketing copy.
        """
        body = response.text if isinstance(response.text, str) else ""
        body_lower = body.lower()

        if vuln_type == 'sqli':
            # Must be a database error message, not just the word "sql"
            error_patterns = [
                "you have an error in your sql syntax",
                "warning: mysql",
                "unclosed quotation mark",
                "quoted string not properly terminated",
                "sqlexception",
                "ora-01756",
                "pg::syntaxerror",
                "sqlite3::exception",
                "syntax error near",
                "unterminated string",
            ]
            return any(p in body_lower for p in error_patterns)

        elif vuln_type == 'xss':
            # Payload must be unescaped in the body (not HTML-encoded)
            # Check that the raw payload appears verbatim, not &lt;script&gt;
            if payload in body:
                encoded = payload.replace("<", "&lt;").replace(">", "&gt;")
                # If the encoded version also appears it might just be escaped output
                # Prefer the raw appearance in a script/event context
                return payload in body and encoded not in body
            return False

        elif vuln_type == 'ssti':
            # Template injection: look for evaluated arithmetic result
            import re
            # Common probes: {{7*7}}=49, ${7*7}=49, <%= 7*7 %>=49
            math_results = re.findall(r'\b(49|7777777)\b', body)
            return bool(math_results)

        elif vuln_type == 'command_injection':
            # Must see actual OS command output, not just an error
            os_indicators = [
                "root:x:0:0",           # /etc/passwd line
                "uid=0(root)",
                "uid=33(www-data)",
                "/bin/bash",
                "/bin/sh",
                "volume serial number",  # Windows dir output
                "windows ip configuration",
            ]
            return any(ind in body_lower for ind in os_indicators)

        elif vuln_type == 'path_traversal':
            # Must see actual file content, not just an error
            file_indicators = [
                "root:x:0:0",         # /etc/passwd
                "[boot loader]",       # Windows boot.ini
                "[operating systems]",
                "for 16-bit app support",
                "daemon:x:",
                "nobody:x:",
            ]
            return any(ind in body_lower for ind in file_indicators)

        return False

    def get_findings(self) -> List[Dict]:
        """Get all findings."""
        return self.findings
